name: "itn"
backend: "python"
max_batch_size: 64
input [
{
    name: "INPUT_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
},
{
    name: "LANG_ID"
    data_type: TYPE_STRING
    dims: [ 1 ]
    reshape { shape: [] }
}
]

output [
{
    name: "OUTPUT_TEXT"
    data_type: TYPE_STRING
    dims: [ 1 ]
}
]

instance_group [
{
  count: 1
  kind: KIND_CPU
}
]
